"""Inicializar tablas de la base de datos

Revision ID: 8e35182a9cab
Revises: 
Create Date: 2026-03-27 01:53:18.977665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e35182a9cab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_calibres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('unidades_por_caja', sa.Integer(), nullable=False),
    sa.Column('peso_promedio_caja_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cultivos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('hectareas', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procesamientos_video',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cultivo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('video_original_url', sa.String(), nullable=False),
    sa.Column('video_anotado_url', sa.String(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_grabacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cultivo_id'], ['cultivos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clasificaciones_manuales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('procesamiento_id', sa.Integer(), nullable=False),
    sa.Column('calibre_id', sa.Integer(), nullable=False),
    sa.Column('estado_madurez', sa.String(length=50), nullable=False),
    sa.Column('cantidad_melones', sa.Integer(), nullable=False),
    sa.Column('cajas_calculadas', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('precio_por_caja_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), sa.Computed('cajas_calculadas * precio_por_caja_aplicado', persisted=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calibre_id'], ['catalogo_calibres.id'], ),
    sa.ForeignKeyConstraint(['procesamiento_id'], ['procesamientos_video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('procesamiento_id', sa.Integer(), nullable=False),
    sa.Column('conteo_maduros', sa.Integer(), nullable=False),
    sa.Column('conteo_inmaduros', sa.Integer(), nullable=False),
    sa.Column('tiempo_procesamiento_seg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['procesamiento_id'], ['procesamientos_video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procesamiento_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_ia')
    op.drop_table('clasificaciones_manuales')
    op.drop_table('procesamientos_video')
    op.drop_table('cultivos')
    op.drop_table('usuarios')
    op.drop_table('catalogo_calibres')
    # ### end Alembic commands ###
